name: Build and Release Next.js CSR App

on:
  push:
    tags:
      - 'v*' # 触发于版本号标签，如 v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 构建 Next.js 应用
        run: |
          npm run build

      - name: 获取仓库名称
        id: repo-name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_OUTPUT
            
      - name: 压缩发布产物
        run: |
              cd dist
              tar -czvf ../${{ steps.repo-name.outputs.REPO_NAME }}.tar.gz .
    
      - name: 创建 GitHub Release
        uses: softprops/action-gh-release@v2
        with:
              files: ${{ steps.repo-name.outputs.REPO_NAME }}.tar.gz
              generate_release_notes: true
        env:
              GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: 登录 GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: 获取版本标签
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: 打包推送 Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: VERSION=${{ steps.get_version.outputs.VERSION }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/${{ github.repository }}:latest
